# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: 'Footer'
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    name: 'Tom Richardson'
    links:
      - name: Home
        url: /
      - name: Blog
        url: /blog
      - name: Contact
        url: /contact
    socials:
      - url: 'www.facebook.com' 
        image: 'images/icons8-facebook-circled-48.png'
      - url: 'www.googlemaps.com' 
        image: 'images/icons8-google-maps-old-48.png'
      - url: 'www.instagram.com' 
        image: 'images/icons8-instagram-48.png'


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    name: 'Tom Richardson'
    links:
      - name: Home
        url: /
      - name: Blog
        url: /blog
      - name: Contact
        url: /contact
    socials:
      - url: 'www.facebook.com' 
        image: 'images/icons8-facebook-circled-48.png'
      - url: 'www.googlemaps.com' 
        image: 'images/icons8-google-maps-old-48.png'
      - url: 'www.instagram.com' 
        image: 'images/icons8-instagram-48.png'

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
