# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: 'Header'
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    links:
      - name: ''
        url: ''

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    links:
      - name: Home
        url: /
      - name: Blog
        url: /blog
      - name: Contact
        url: /contact

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
