# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: 'Blog'
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    section_title: 'Latest Writings'
    featured_post_one:
      title: 'My First Post'
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima rerum tempore ipsam nesciunt eius officiis quae. Dicta temporibus deserunt in!'
      image:
        url: 'http://www.placekitten.com/600/300'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
  section_title: 'Latest Writings'
  featured_post_one:
    title: 'My First Post'
    description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima rerum tempore ipsam nesciunt eius officiis quae. Dicta temporibus deserunt in!'
    image:
      url: 'http://www.placekitten.com/600/300'

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
